import daisyui from "daisyui";

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {},
  },
  plugins: [daisyui],
  daisyui: {
    themes: [
      "light",
      "dark",
      "cupcake",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "dracula",
      "shades-of-purple",
      "teal",
      "modern",
      "classic",
      "cool",
      "acid",
      "crimson",
      "ember",
      "ocean",
      "italian",
      "ukraine",
      "india",
      "lemonade",
      "mexico",
      "vintage",
      "japan",
      "china",
      "coffee",
      "purple",
      "pink",
      "blue",
      "green",
      "red",
      "garden",
      "forest",
      "winter",
      "autumn",
    ],
  },
};
